facts = [
    ## Space
    "The Sun accounts for about 99.8% of the total mass of the solar system.",
    "A day on Venus is longer than a year on Venus.",
    "Neutron stars can spin at a rate of hundreds of rotations per second.",
    "The footprints on the Moon will likely stay there for millions of years since there's no wind to erode them.",
    "Jupiter has the shortest day of any planet in the solar system, rotating once in about 10 hours.",
    "There are more stars in the observable universe than grains of sand on all of Earth's beaches.",
    "Saturn is so low in density that it would float in water if there were an ocean big enough.",
    "The largest known star, UY Scuti, is so big it would take a beam of light over 1,100 seconds to travel around it once.",
    "Light from the Sun takes about 8 minutes and 20 seconds to reach Earth.",
    "The Milky Way galaxy is on a collision course with the Andromeda galaxy, expected to merge in about 4.5 billion years.",
    "Mars has the largest volcano in the solar system, Olympus Mons, roughly three times taller than Mount Everest.",
    "One million Earths could fit inside the Sun.",
    "The temperature on Mercury can swing from about 430°C in the day to -180°C at night.",
    "There is a planet made largely of diamond, known as 55 Cancri e.",
    "Astronauts can grow up to two inches taller in space due to the lack of gravity compressing their spine.",
    "The International Space Station travels at roughly 28,000 kilometers per hour.",
    "Space is completely silent because sound waves need a medium like air to travel through.",
    "A full NASA space suit costs around 12 million dollars.",
    "The Moon is very slowly drifting away from Earth at a rate of about 3.8 centimeters per year.",
    "Black holes can slow down time in their vicinity due to their intense gravity.",
    "Venus is the hottest planet in the solar system, even hotter than Mercury, due to its thick atmosphere.",
    "Saturn's rings are made mostly of ice particles, with a smaller amount of rocky debris and dust.",
    "It would take about 9 years to drive a car to the Moon if roads existed.",
    "The largest volcano discovered on any planet, Olympus Mons, is about 21 kilometers high.",
    "Pluto has not completed even one full orbit of the Sun since its discovery in 1930.",
    "There are more possible chess games than atoms in the observable universe.",
    "The coldest known place in the universe is the Boomerang Nebula, at about -272°C.",
    "Comets are sometimes called dirty snowballs because they're made of ice, dust, and rocky material.",
    "The word 'planet' comes from the Greek word for 'wanderer.'",
    "A year on Mercury lasts just 88 Earth days.",
    "Uranus rotates on its side, likely due to a massive collision billions of years ago.",
    "The largest known asteroid, Ceres, is also classified as a dwarf planet.",
    "The Hubble Space Telescope has captured images of galaxies over 13 billion light-years away.",
    "There is a giant storm on Jupiter, the Great Red Spot, that has been raging for hundreds of years.",
    "The Sun is classified as a yellow dwarf star, though it actually emits white light.",
    "Astronomers estimate there could be more Earth-like planets in the universe than grains of sand on Earth.",
    "The Apollo 11 mission's computer had far less processing power than a modern smartphone.",
    "Saturn's moon Titan has lakes and rivers, but they're made of liquid methane rather than water.",
    "A shooting star is not actually a star, but a small piece of debris burning up in Earth's atmosphere.",
    "The gravitational pull of the Moon is the main cause of Earth's ocean tides.",

    ## Animals
    "Octopuses have three hearts and blue blood.",
    "A group of flamingos is called a flamboyance.",
    "Elephants are one of the few animals that can recognize themselves in a mirror.",
    "Honey never spoils if stored properly, and archaeologists have found edible honey in ancient Egyptian tombs.",
    "A shrimp's heart is located in its head.",
    "Sea otters hold hands while sleeping so they don't drift apart.",
    "The heart of a blue whale is roughly the size of a small car.",
    "Cows have best friends and can become stressed when separated from them.",
    "A single strand of spider silk is stronger by weight than a strand of steel.",
    "Koalas have fingerprints so similar to humans that they can occasionally confuse crime scene investigators.",
    "Dolphins have names for each other in the form of unique signature whistles.",
    "A snail can sleep for up to three years at a time.",
    "The mantis shrimp can punch with the force and acceleration of a bullet.",
    "Some turtles can breathe through their butts, a process called cloacal respiration.",
    "Giraffes only need about 30 minutes to two hours of sleep per day.",
    "A group of crows is called a murder.",
    "Wombat droppings are cube-shaped.",
    "Cats can't taste sweetness because they lack the necessary taste receptor.",
    "Elephants are the only mammals that can't jump.",
    "The tongue of a blue whale weighs as much as an adult elephant.",
    "A group of pandas is called an embarrassment.",
    "Butterflies taste with their feet.",
    "Some species of jellyfish are biologically immortal and can reverse their aging process.",
    "A crocodile cannot stick its tongue out.",
    "Owls can rotate their heads about 270 degrees.",
    "The Greenland shark can live for several hundred years, making it one of the longest-living vertebrates.",
    "Starfish don't have brains or blood.",
    "A group of owls is called a parliament.",
    "Kangaroos can't walk backward.",
    "Pigeons can be trained to recognize the difference between real paintings and forgeries.",
    "A hummingbird's heart can beat over 1,200 times per minute during flight.",
    "Sloths can hold their breath longer than dolphins can.",
    "Some ants can carry objects up to 50 times their own body weight.",
    "Polar bears have black skin under their white fur.",
    "A shrimp can propel itself so fast that the water around it can boil momentarily due to friction.",
    "Male seahorses, not females, are the ones who carry and give birth to their young.",
    "Elephants can communicate over long distances using low-frequency sounds that travel through the ground.",
    "A cheetah can accelerate from 0 to 60 miles per hour in about three seconds.",
    "Bats are the only mammals capable of true, sustained flight.",
    "Some species of frogs can survive being frozen almost solid during winter.",

    ## Human Body
    "The human body contains enough carbon to fill about 9,000 pencils.",
    "Your bones are about five times stronger than steel of the same weight.",
    "The human brain uses about 20% of the body's total energy despite being roughly 2% of its weight.",
    "It's impossible to tickle yourself due to how the brain processes expected sensations.",
    "The acid in your stomach is strong enough to dissolve metal over time.",
    "Your body produces about a liter of saliva a day.",
    "Human fingernails grow faster than toenails.",
    "The human heart beats around 100,000 times a day.",
    "Every person has a unique tongue print, much like a fingerprint.",
    "The human eye can distinguish about 10 million different colors.",
    "Bones make up about 15% of your total body weight.",
    "The small intestine is about 22 feet long in an adult.",
    "Your skin is the largest organ in your body.",
    "Humans shed about 30,000 to 40,000 dead skin cells every hour.",
    "The human nose can detect over a trillion distinct scents.",
    "Babies are born with about 300 bones, while adults have only 206, because some fuse together over time.",
    "Your brain generates enough electricity to power a small light bulb.",
    "Human teeth are almost as hard as rock.",
    "It takes the average person about seven minutes to fall asleep.",
    "Blood makes up roughly 7-8% of a person's total body weight.",
    "The human body contains around 37 trillion cells.",
    "Muscles and fat take up roughly the same volume, but muscle weighs more than fat.",
    "Your ears and nose continue growing very slowly throughout your entire life.",
    "The strongest muscle in the human body relative to its size is the masseter, used for chewing.",
    "The human body has enough iron in it to make a small nail.",
    "Adults typically breathe about 12 to 20 times per minute at rest.",
    "The surface of the lungs, if unfolded, would cover the area of a tennis court.",
    "Your left lung is smaller than your right lung to make room for your heart.",
    "The human body sheds and regrows its outer skin layer roughly every 27 days.",
    "Humans lose about half a liter of water a day just through breathing.",
    "The human brain can process images seen for as little as 13 milliseconds.",
    "A sneeze can travel out of your body at speeds up to 100 miles per hour.",
    "Your body contains about 60,000 miles of blood vessels.",
    "The human body's most sensitive part per square inch is the fingertip.",
    "It's estimated the average person walks the equivalent of five times around the world in a lifetime.",
    "Your liver can regenerate itself even after losing up to 75% of its tissue.",
    "Human hair is made of the same protein, keratin, found in animal claws and hooves.",
    "The femur, or thigh bone, is the longest and strongest bone in the human body.",
    "Adults have about 1 to 2 million sweat glands across their skin.",
    "Your body temperature naturally fluctuates throughout the day, usually lowest in early morning.",

    ## Ocean
    "More than 80% of the ocean remains unexplored and unmapped.",
    "The Pacific Ocean is larger than all of Earth's landmass combined.",
    "The deepest part of the ocean, the Mariana Trench, is deeper than Mount Everest is tall.",
    "The ocean produces more than half of the world's oxygen, largely from marine plants like phytoplankton.",
    "There are underwater lakes and rivers on the ocean floor, formed by dense saltwater pockets.",
    "The blue whale is the largest animal to have ever lived on Earth, even larger than any known dinosaur.",
    "Sound travels roughly four times faster in water than it does in air.",
    "The ocean contains about 97% of Earth's water.",
    "There are more historical artifacts under the sea than in all the world's museums combined.",
    "Some parts of the ocean are so deep that sunlight never reaches the bottom.",
    "The Great Barrier Reef is the largest living structure on Earth and is visible from space.",
    "Icebergs can hold ancient air bubbles trapped from thousands of years ago.",
    "The ocean's average depth is about 12,000 feet.",
    "Certain species of octopus can change both their color and texture to match their surroundings almost instantly.",
    "Sharks existed on Earth before trees did.",
    "The Dead Sea is so salty that it's nearly impossible for a person to sink while floating in it.",
    "Sea levels have risen by about 8 inches since 1900 due to a combination of factors including melting ice.",
    "Ocean currents help regulate the Earth's climate by transporting heat around the globe.",
    "There are underwater waterfalls, such as the one off the coast of Mauritius, created by sand and silt deposits.",
    "The colossal squid has the largest eyes in the animal kingdom, roughly the size of a soccer ball.",
    "Coral reefs cover less than 1% of the ocean floor but support around 25% of all marine species.",
    "Some fish can produce their own light through a process called bioluminescence.",
    "The Atlantic Ocean is slowly widening by a few centimeters every year due to plate tectonics.",
    "There's enough gold dissolved in the ocean to give every person on Earth several pounds, though it's far too diluted to extract profitably.",
    "The ocean absorbs roughly a quarter of the carbon dioxide humans release into the atmosphere.",
    "The Mariana Trench experiences pressure over 1,000 times greater than at sea level.",
    "Whale songs can travel for hundreds of miles underwater.",
    "There are entire ecosystems around deep-sea hydrothermal vents that survive without sunlight.",
    "The ocean floor has mountain ranges longer than any found on land.",
    "Some jellyfish species have been around for over 500 million years, predating dinosaurs.",
    "A single teaspoon of seawater can contain millions of microorganisms.",
    "The Arctic Ocean is the smallest and shallowest of the world's five oceans.",
    "Sea turtles can hold their breath for several hours while resting underwater.",
    "The ocean's tides are influenced by both the Moon and the Sun's gravitational pull.",
    "There are underwater volcanoes, and most volcanic activity on Earth actually happens beneath the ocean.",
    "Certain species of sea cucumbers can expel their internal organs as a defense mechanism, then regenerate them.",
    "The ocean holds an estimated 20 million tons of gold, dissolved in trace amounts throughout its waters.",
    "Some areas of the ocean are so remote that the nearest humans are astronauts on the International Space Station.",
    "The world's longest mountain range, the Mid-Ocean Ridge, is almost entirely underwater.",
    "Manta rays have the largest brain-to-body ratio of any fish.",

    ## History
    "The Great Wall of China isn't a single continuous wall but a series of walls built by different dynasties.",
    "Cleopatra lived closer in time to the invention of the iPhone than to the construction of the Great Pyramid of Giza.",
    "Oxford University is older than the Aztec Empire.",
    "Ancient Romans used urine as a mouthwash because of its ammonia content.",
    "The shortest war in recorded history lasted under 40 minutes, between Britain and Zanzibar in 1896.",
    "The first recorded Olympic Games took place in ancient Greece in 776 BCE.",
    "Napoleon Bonaparte was actually of average height for his time, despite his popular image as being unusually short.",
    "The Eiffel Tower can grow taller in the summer due to thermal expansion of the metal.",
    "Vikings used the bones of animals to make ice skates.",
    "The ancient Egyptians used a form of toothpaste made from crushed eggshells and ox hooves.",
    "The first known written language, cuneiform, was developed by the Sumerians around 3400 BCE.",
    "Ancient Greek and Roman statues were originally painted in bright colors, though the paint has faded over time.",
    "The printing press, invented by Johannes Gutenberg, dramatically increased the spread of literacy in Europe.",
    "Ancient Chinese inventors are credited with creating gunpowder, originally for medicinal purposes.",
    "The Library of Alexandria was one of the largest and most significant libraries of the ancient world before its eventual decline.",
    "Medieval knights typically couldn't get up if they fell over in full armor without help.",
    "The Statue of Liberty was originally a copper color before oxidizing to its now-famous green patina.",
    "World War I officially ended at the eleventh hour of the eleventh day of the eleventh month in 1918.",
    "The ancient city of Pompeii was preserved remarkably well after being buried by volcanic ash from Mount Vesuvius in 79 CE.",
    "The first computer programmer is widely considered to be Ada Lovelace, in the 19th century.",
    "The Berlin Wall stood for 28 years before being torn down in 1989.",
    "Ancient Mesopotamians developed one of the earliest known systems of writing and law.",
    "The Titanic's wreckage wasn't discovered until 1985, over seven decades after it sank.",
    "The first man-made object to reach space was a German V-2 rocket during World War II.",
    "The Magna Carta, signed in 1215, laid groundwork for modern ideas of legal rights and limited government.",
    "Ancient Roman roads were engineered so well that some are still in use today.",
    "The pyramids of Giza were built without the use of wheels for transporting the massive stone blocks.",
    "The Renaissance period saw a major revival of art, science, and culture in Europe following the Middle Ages.",
    "The first email was sent in 1971 by computer engineer Ray Tomlinson.",
    "Ancient Aztec society valued cacao beans so highly they were sometimes used as a form of currency.",
    "Julius Caesar was captured by pirates in his youth and later returned to have them executed.",
    "The Wright brothers' first powered flight in 1903 lasted only 12 seconds.",
    "The ancient Olympics only allowed free men who spoke Greek to compete.",
    "The Rosetta Stone was key to deciphering ancient Egyptian hieroglyphics.",
    "The Cold War, despite its name, involved numerous proxy conflicts fought around the world.",
    "Handshakes are believed to have originated as a way to show that neither party was carrying a weapon.",
    "The ancient Inca civilization built an extensive road system across the Andes without the use of the wheel.",
    "The first recorded use of the phrase 'the whole nine yards' remains debated among historians.",
    "The Hundred Years' War between England and France actually lasted 116 years.",
    "Genghis Khan's empire was the largest contiguous land empire in history.",

    ## Geography
    "Russia spans eleven different time zones.",
    "The Sahara Desert is roughly the same size as the entire United States.",
    "Alaska is the state that is both the furthest north, west, and east in the United States.",
    "Mount Everest grows a few millimeters taller every year due to tectonic plate movement.",
    "There are more than 7,000 islands in the Philippines archipelago.",
    "Antarctica is technically classified as a desert due to its extremely low precipitation.",
    "Canada has the longest coastline of any country in the world.",
    "The Amazon rainforest produces roughly 20% of the world's oxygen.",
    "The Dead Sea is the lowest point on Earth's land surface, at about 430 meters below sea level.",
    "Vatican City is the smallest country in the world, both by area and population.",
    "Africa is the only continent that spans all four hemispheres.",
    "Iceland has no native mosquito population.",
    "Australia is wider than the Moon.",
    "There is a lake in Bolivia, the Uyuni Salt Flat, that turns into a giant mirror when it rains.",
    "The longest place name in the world is a hill in New Zealand with over 80 letters.",
    "Chile is the longest north-to-south country in the world, stretching over 4,300 kilometers.",
    "The Nile River is often cited as the longest river in the world, though the Amazon River's length is also debated by some sources.",
    "There's a border town where the international boundary runs directly through a library, splitting it between the US and Canada.",
    "The driest place on Earth is the Atacama Desert in Chile, where some areas haven't recorded rainfall in centuries.",
    "Bhutan measures national success partly through Gross National Happiness instead of only GDP.",
    "Mount Kilimanjaro is the tallest freestanding mountain in the world, not part of a larger mountain range.",
    "Turkey is the only country located on two continents, straddling both Europe and Asia.",
    "The Amazon River discharges more water than the next seven largest rivers in the world combined.",
    "Norway has more fjords than any other country due to its glacially carved coastline.",
    "The world's largest hot desert, the Sahara, continues to expand due to changing climate patterns.",
    "There is a river in Colombia, Caño Cristales, known for turning vibrant shades of red, yellow, and green.",
    "Greenland is the world's largest island that isn't classified as a continent.",
    "The equator passes through 13 countries around the globe.",
    "Lake Baikal in Russia is the deepest and oldest freshwater lake in the world.",
    "Monaco is the second smallest country in the world, right after Vatican City.",
    "Death Valley in California holds the record for the highest recorded air temperature on Earth.",
    "There's a desert in Namibia where sand dunes meet the ocean directly.",
    "The Ring of Fire, a horseshoe-shaped zone around the Pacific Ocean, is home to most of the world's active volcanoes.",
    "New Zealand was one of the last major landmasses to be settled by humans.",
    "The Strait of Gibraltar separates Europe from Africa by only about 13 kilometers at its narrowest point.",
    "Indonesia is made up of more than 17,000 islands.",
    "The world's largest coral reef system, the Great Barrier Reef, stretches over 2,300 kilometers.",
    "Switzerland has more mountains over 4,000 meters than almost any other country in Europe.",
    "The Danube River flows through more countries than any other river in the world.",
    "Mongolia has one of the lowest population densities of any country on Earth.",

    ## Science
    "Water can boil and freeze at the same time under specific pressure and temperature conditions, known as the triple point.",
    "A bolt of lightning is roughly five times hotter than the surface of the Sun.",
    "Glass is technically considered an amorphous solid rather than a true crystalline solid.",
    "Diamonds are not the rarest gemstone; several others, like red beryl, are significantly rarer.",
    "Bananas are naturally slightly radioactive due to their potassium content, though harmlessly so.",
    "Sound cannot travel through the vacuum of space because there's no medium to carry the waves.",
    "Helium can make your voice sound higher because sound travels faster through it than through air.",
    "The only letter that doesn't appear in the periodic table of elements is the letter J.",
    "A single bolt of lightning contains enough energy to toast about 100,000 slices of bread.",
    "Hot water can freeze faster than cold water under certain conditions, a phenomenon known as the Mpemba effect.",
    "Metal doesn't actually feel colder than wood at room temperature; it just conducts heat away from your skin faster.",
    "Gold is so malleable that a single ounce can be stretched into a wire over 80 kilometers long.",
    "There are more possible iterations of a shuffled deck of cards than there are atoms on Earth.",
    "The average cloud can weigh over a million pounds due to the volume of water droplets it contains.",
    "Human DNA is about 60% similar to that of a banana.",
    "Static electricity can generate sparks reaching temperatures around 3,000°C, hotter than the surface of most stars.",
    "Rubber bands last longer when kept cold, since heat and light break down their elasticity faster.",
    "A pencil can draw a line about 35 miles long before running out of graphite.",
    "The chemical formula for table salt is NaCl, made from sodium and chlorine, both of which are dangerous on their own.",
    "Some metals, like gallium, can melt in the palm of your hand due to their low melting point.",
    "Antimatter is the most expensive material known, costing an estimated 62.5 trillion dollars per gram to produce.",
    "The Earth's magnetic field periodically flips polarity over geological timescales.",
    "Water expands by about 9% when it freezes, which is why ice floats.",
    "The color of a flame can indicate its temperature, with blue flames typically burning hotter than orange ones.",
    "Some crystals can take millions of years to form under the right geological conditions.",
    "The human body technically glows, emitting light too faint for the naked eye to detect.",
    "There is enough energy released in a single average hurricane to power the entire United States for weeks.",
    "The periodic table is arranged by increasing atomic number, not atomic weight.",
    "It's theoretically possible to turn lead into gold using nuclear reactions, though the process is extremely costly.",
    "Quantum entanglement allows particles to affect each other's states instantly, regardless of distance.",
    "A teaspoon of a neutron star would weigh about 6 billion tons on Earth.",
    "Sound waves can be used to levitate small objects using a phenomenon called acoustic levitation.",
    "The Earth's core is estimated to be nearly as hot as the surface of the Sun.",
    "Plastic can take hundreds to thousands of years to decompose depending on the type and environment.",
    "Certain frogs and insects contain natural antifreeze compounds that let them survive freezing temperatures.",
    "The speed of light is approximately 299,792 kilometers per second in a vacuum.",
    "Static shocks from everyday objects can reach thousands of volts, though usually with very low current.",
    "Some bacteria can survive in extreme environments, such as inside nuclear reactors or deep-sea vents.",
    "Water is one of the few substances that is less dense as a solid than as a liquid.",
    "The concept of absolute zero, the coldest possible temperature, is theorized at -273.15°C.",

    ## Technology
    "The first computer mouse was made of wood.",
    "The first message sent over the internet was meant to say 'LOGIN,' but the system crashed after just two letters.",
    "The QWERTY keyboard layout was originally designed to slow typists down and reduce mechanical typewriter jams.",
    "More than 500 hours of video are uploaded to YouTube every single minute.",
    "The first computer virus was created in the early 1970s as an experiment, not for malicious purposes.",
    "The term 'bug' in computing is said to date back to an actual moth found in an early computer relay.",
    "The first text message ever sent simply said 'Merry Christmas.'",
    "Early computers used punch cards to store and process data before digital storage existed.",
    "A modern smartphone has significantly more processing power than the computers used for the Apollo Moon missions.",
    "The world's first website, created by Tim Berners-Lee, is still viewable online today.",
    "Wi-Fi doesn't actually stand for anything; it was originally just a catchy marketing term.",
    "The first domain name ever registered was in 1985.",
    "Bluetooth technology is named after a 10th-century Scandinavian king known for uniting tribes.",
    "The first hard disk drive, developed in the 1950s, could store only a few megabytes of data.",
    "The first 1GB hard drive, released in 1980, weighed about 550 pounds.",
    "There are more devices connected to the internet today than there are people on Earth.",
    "The @ symbol used in email addresses predates the internet by centuries, originally used in commerce.",
    "The first widely used web browser, Mosaic, was released in 1993.",
    "Early video game consoles had far less processing power than a modern digital calculator.",
    "The password '123456' remains one of the most commonly used, and least secure, passwords in the world.",
    "The first webcam was created to monitor a coffee pot so researchers wouldn't waste trips checking it.",
    "Approximately 90% of the world's currency exists only in digital form.",
    "The concept of the 'cloud' in computing simply refers to servers accessed over the internet, not an actual cloud.",
    "The first ever computer programmer, Ada Lovelace, wrote an algorithm for a machine that was never built in her lifetime.",
    "Email existed before the World Wide Web was invented.",
    "The first iPhone was released in 2007, fundamentally changing how people interact with mobile technology.",
    "The binary code system, using only 0s and 1s, underpins nearly all modern computing.",
    "Early computers, like ENIAC, took up entire rooms and weighed several tons.",
    "The first computer game, created in the 1950s, was a simple version of tic-tac-toe.",
    "Modern data centers consume vast amounts of electricity, some rivaling the power usage of small cities.",
    "GPS technology relies on a network of satellites orbiting the Earth to determine precise locations.",
    "The term 'spam' for unwanted messages originates from a Monty Python sketch about canned meat.",
    "The first computer mouse patent was filed in 1970, though the device was invented a few years earlier.",
    "USB was designed to be a universal standard, replacing a wide variety of previous connector types.",
    "Early telephones had no dial or keypad; users had to speak to an operator to connect calls.",
    "The average person checks their smartphone dozens of times per day.",
    "Social media platforms often use algorithms specifically designed to maximize user engagement and time spent.",
    "The concept of artificial intelligence dates back to ideas explored by mathematicians and philosophers long before modern computers existed.",
    "The first online purchase is believed to have been a CD, bought through an early e-commerce platform in 1994.",
    "Fiber optic cables transmit data using light rather than electrical signals, allowing for extremely high speeds.",

    ## Food
    "Honey is one of the only foods that never spoils if stored correctly.",
    "Carrots were originally purple before orange varieties became more common.",
    "Apples float in water because they are made up of roughly 25% air.",
    "Chocolate was once used as currency by ancient Mesoamerican civilizations.",
    "Peanuts are not technically nuts; they are classified as legumes.",
    "The world's most expensive spice, saffron, must be harvested entirely by hand.",
    "Tomatoes are botanically classified as fruits, though commonly treated as vegetables in cooking.",
    "White chocolate isn't technically chocolate because it contains no cocoa solids.",
    "Almonds are part of the same plant family as peaches and cherries.",
    "The fear of cooking is known as mageirocophobia.",
    "Cashews grow attached to the bottom of a fruit called the cashew apple.",
    "Ketchup was once sold in the 1800s as a medicine believed to cure various ailments.",
    "A cluster of bananas is called a hand, and a single banana is called a finger.",
    "Rice is a staple food for more than half of the world's population.",
    "Pineapples take about two to three years to grow and mature.",
    "The world's hottest chili peppers can rank millions of units on the Scoville scale, the measure of spiciness.",
    "Vanilla is the second most expensive spice in the world, after saffron.",
    "Cucumbers are made up of about 95% water.",
    "Watermelon is technically classified as both a fruit and a vegetable.",
    "Chili peppers were historically used in some cultures as a natural pepper spray for self-defense.",
    "The world's largest pizza ever made covered an area larger than a football field.",
    "Grapes can explode if placed in a microwave due to how microwaves interact with their internal structure.",
    "Cheese is one of the oldest processed foods, dating back thousands of years.",
    "Some varieties of honey never spoil because of their low moisture content and acidic pH.",
    "Coffee beans are technically the seeds of a fruit called the coffee cherry.",
    "The world's most expensive coffee is made from beans that have passed through a civet's digestive system.",
    "Popcorn has been enjoyed as a snack for thousands of years, with evidence dating back to ancient civilizations in the Americas.",
    "Strawberries are not technically berries, but bananas actually are.",
    "The average person eats several pounds of insects unknowingly each year through processed foods.",
    "Mushrooms share more genetic similarities with animals than with plants.",
    "Corn cannot reproduce on its own without human cultivation.",
    "There are more than 7,500 known varieties of apples grown worldwide.",
    "Chewing gum has existed in some form for thousands of years, originally made from tree resin.",
    "Lemons contain more sugar than strawberries, though they taste sour due to their high acidity.",
    "The world's most expensive burger has sold for thousands of dollars, made with luxury ingredients like wagyu beef and truffles.",
    "Broccoli contains more protein per calorie than a comparable amount of steak.",
    "Onions can make you cry due to a chemical compound released when their cells are damaged.",
    "The world record for the largest chocolate bar weighed over 12,000 pounds.",
    "Potatoes were the first vegetable to be grown in space.",
    "Cinnamon comes from the bark of a tree and has been used since ancient times both as a spice and for its medicinal properties.",

    ## Language
    "The word 'set' has more definitions than any other word in the English language.",
    "There are more than 7,000 spoken languages in use around the world today.",
    "The shortest complete sentence in the English language is 'Go.'",
    "The dot above a lowercase 'i' or 'j' is called a tittle.",
    "English borrows words from more than 350 different languages.",
    "The longest word in major English dictionaries relates to a lung disease and has 45 letters.",
    "Sign languages are not universal; different countries often have entirely distinct sign languages.",
    "The word 'nerd' first appeared in a Dr. Seuss book in 1950.",
    "There is no official language of the United States at the federal level.",
    "The Hawaiian alphabet has only 13 letters.",
    "Many languages have words that don't translate directly into English, describing very specific feelings or experiences.",
    "Old English is so different from modern English that most speakers today can't understand it without study.",
    "The word 'alphabet' comes from the first two letters of the Greek alphabet, alpha and beta.",
    "Mandarin Chinese has the most native speakers of any language in the world.",
    "The exclamation mark was not originally part of typewriters and had to be typed using multiple keystrokes.",
    "Some languages, like Finnish, have no future tense grammatically; context indicates future events instead.",
    "The word 'robot' comes from a Czech word meaning forced labor.",
    "English is considered a Germanic language, though much of its vocabulary comes from Latin and French.",
    "There are click consonants used in some African languages that don't exist in most other language families.",
    "The longest place name in the world, found in New Zealand, has 85 letters.",
    "Many languages assign grammatical gender to nouns, a feature English largely lost over time.",
    "The word 'goodbye' evolved from the phrase 'God be with you.'",
    "Icelandic has changed so little over centuries that modern speakers can read texts nearly a thousand years old.",
    "Emoji are technically considered their own visual language by some linguists.",
    "The word 'quiz' is rumored, though disputed, to have been invented on a bet in 18th century Dublin.",
    "There are more than 20 different sign languages used just across Europe.",
    "The English language has no true synonym for the word 'orange' as a color that isn't derived from the fruit.",
    "Some languages have words specifically for the smell of rain on dry earth.",
    "The word 'OK' is considered one of the most recognized words across the entire world.",
    "Many idioms in English, like 'raining cats and dogs,' have murky and debated origins.",
    "The pangram 'The quick brown fox jumps over the lazy dog' contains every letter of the English alphabet.",
    "The most commonly spoken second language in the world is English.",
    "The word 'muscle' comes from the Latin word for 'little mouse,' due to how muscles look like they move under the skin.",
    "Sanskrit is considered one of the oldest documented languages still studied today.",
    "The letter 'E' is the most commonly used letter in the English language.",
    "Some words in English change meaning entirely depending on stress or emphasis, called heteronyms.",
    "Braille was invented by a teenager, Louis Braille, who lost his sight as a child.",
    "The word 'trivia' comes from Latin, referring to the meeting of three roads, symbolizing common or basic knowledge.",
    "Esperanto was created in the late 1800s as an attempt to build a universal second language.",
    "Many languages, like Arabic, are written and read from right to left rather than left to right.",

    ## Sports
    "The modern Olympic Games began in 1896 in Athens, Greece.",
    "A marathon's official distance, 26.2 miles, was standardized based on the 1908 London Olympics course.",
    "Basketball was invented by James Naismith in 1891 using a peach basket as the original hoop.",
    "The fastest recorded serve in tennis has exceeded 160 miles per hour.",
    "Golf balls have dimples specifically to reduce air resistance and improve flight distance.",
    "The World Cup is the most-watched sporting event on the planet, surpassing even the Olympics in global viewership.",
    "Table tennis balls can travel at speeds exceeding 60 miles per hour during a competitive rally.",
    "The Tour de France covers roughly 2,200 miles over about three weeks.",
    "American football fields are 100 yards long, not including the end zones.",
    "Boxing gloves were introduced partly to protect the hands of the boxer as much as the opponent's face.",
    "Cricket matches can last up to five days in the traditional Test match format.",
    "Ice hockey pucks are frozen before games to reduce bouncing on the ice.",
    "The Ironman triathlon consists of a 2.4-mile swim, a 112-mile bike ride, and a full 26.2-mile marathon.",
    "The dimensions of a soccer field can vary, unlike many other major sports with fixed field sizes.",
    "Sumo wrestling has a history spanning over 1,500 years in Japan.",
    "Rugby is credited with originating when a schoolboy allegedly picked up a soccer ball and ran with it in 1823.",
    "The Olympic torch relay tradition began at the 1936 Berlin Olympics.",
    "Baseball's World Series is called that despite primarily featuring teams from the United States and Canada.",
    "Swimmers often shave their body hair to reduce drag and improve speed in competition.",
    "Chess is recognized as an official sport by the International Olympic Committee, though not currently included in the Games.",
    "The fastest human running speed ever recorded exceeded 27 miles per hour.",
    "Badminton shuttlecocks can travel faster than any other object used in racquet sports.",
    "The Green Jacket awarded at the Masters golf tournament has been a tradition since 1949.",
    "Wimbledon is the oldest tennis tournament in the world, first held in 1877.",
    "Gymnastics scoring changed from a perfect 10 system to an open-ended scale in 2006.",
    "American football helmets became mandatory in the NFL only in the 1940s.",
    "Curling stones are made of a specific type of granite found in only a few locations worldwide.",
    "The Boston Marathon is the oldest annual marathon in the world, first run in 1897.",
    "Volleyball was originally called 'mintonette' when it was invented in 1895.",
    "Formula 1 cars can accelerate from 0 to 60 miles per hour in under two seconds.",
    "The longest tennis match in history lasted over 11 hours across three days.",
    "Surfing has origins tracing back over a thousand years to Polynesian culture.",
    "The Stanley Cup, awarded in ice hockey, is the oldest trophy competed for by professional athletes in North America.",
    "Weightlifting has been part of the modern Olympics since the very first Games in 1896.",
    "Archery was once a mandatory skill taught for both hunting and warfare before becoming a competitive sport.",
    "The dimensions of a basketball hoop have remained largely unchanged since the sport's invention.",
    "Fencing is one of only a handful of sports to have been included in every modern Olympic Games.",
    "Cricket bats are traditionally made from willow wood due to its lightweight, shock-absorbing qualities.",
    "The longest home run ever recorded in professional baseball traveled well over 500 feet.",
    "Skateboarding became an official Olympic sport starting with the Tokyo 2020 Games.",

    ## Nature
    "Bamboo is one of the fastest-growing plants on Earth, with some species growing nearly a meter in a single day.",
    "A single tree can absorb roughly 48 pounds of carbon dioxide per year.",
    "Rainforests, despite covering a small percentage of Earth's surface, are home to more than half of the world's plant and animal species.",
    "Lightning strikes the Earth roughly 8 million times per day.",
    "The tallest tree in the world, a coast redwood, stands over 379 feet tall.",
    "Some plants, like the Venus flytrap, have evolved to trap and digest insects for nutrients.",
    "Deserts cover roughly one-third of the Earth's land surface.",
    "Fungi form some of the largest living organisms on Earth, with certain networks spanning several square miles underground.",
    "A rainbow is actually a full circle, but we typically only see the arc from the ground.",
    "Certain trees can communicate and share resources with each other through underground fungal networks.",
    "Volcanic soil is often extremely fertile, which is why many volcanic regions support rich agriculture.",
    "The world's oldest known living tree is estimated to be over 4,800 years old.",
    "Snowflakes, while often described as unique, can occasionally form identical twin crystals under rare conditions.",
    "Some forests can generate their own weather patterns due to the amount of moisture they release into the atmosphere.",
    "Glaciers store roughly 69% of the world's fresh water.",
    "The Amazon rainforest is home to an estimated 400 billion individual trees.",
    "Certain plant species can lie dormant as seeds for decades or even centuries before germinating.",
    "A single mature oak tree can produce thousands of acorns in a good growing season.",
    "Wind and water erosion have carved some of the most dramatic natural landmarks on Earth over millions of years.",
    "Some flowers, like the corpse flower, produce an intense smell of rotting flesh to attract pollinators.",
    "Earth's atmosphere is made up of roughly 78% nitrogen and 21% oxygen.",
    "Coral reefs are actually made up of colonies of tiny living organisms called polyps.",
    "The driest desert in the world receives less rainfall in a year than most cities get in a single storm.",
    "Certain species of trees can live for thousands of years, far outliving nearly all other living things on Earth.",
    "Moss doesn't have roots; it absorbs water and nutrients directly through its leaves.",
    "A hurricane can release the energy equivalent of thousands of nuclear bombs over its lifetime.",
    "Certain mushroom species can glow in the dark due to a chemical reaction called bioluminescence.",
    "The Sahara Desert was once a lush, green landscape thousands of years ago before shifting into the desert it is today.",
    "Peat bogs can preserve organic material, including ancient human remains, for thousands of years.",
    "Some seeds are specifically designed to only germinate after being exposed to fire.",
    "The Earth's tectonic plates move at roughly the same speed that human fingernails grow.",
    "Certain species of algae can bloom so intensely they turn entire bodies of water vibrant shades of red or green.",
    "A single lightning bolt can heat the surrounding air to temperatures hotter than the surface of the Sun.",
    "Some caves contain crystal formations that have taken hundreds of thousands of years to grow.",
    "Wildfires, while destructive, are a natural and necessary part of some ecosystems' regeneration cycles.",
    "Certain species of trees can detect and respond chemically to insect attacks by producing defensive compounds.",
    "The Northern Lights are caused by charged particles from the Sun colliding with Earth's atmosphere.",
    "Earth's rotation is gradually slowing down, adding about 1.7 milliseconds to the length of a day per century.",
    "Some deserts experience dramatic temperature swings, from scorching heat by day to freezing cold at night.",
    "Mount Everest's summit is technically closer to space than to sea level due to Earth's slightly flattened shape.",

    ## World Records
    "The tallest man ever recorded stood at 8 feet 11 inches tall.",
    "The largest pizza ever made covered an area of over 13,000 square feet.",
    "The longest fingernails ever recorded on a single hand measured over 30 feet combined.",
    "The world's largest sandcastle stood taller than a ten-story building.",
    "The longest recorded flight of a paper airplane stayed airborne for over 27 seconds.",
    "The largest gathering of people dressed as superheroes set a record with thousands of participants.",
    "The world's longest fingernail on a single finger measured over five feet long.",
    "The largest snowflake ever recorded reportedly measured 15 inches across.",
    "The most tattoos received in 24 hours by one person exceeded 800 individual tattoos.",
    "The world's longest human chain involved hundreds of thousands of participants linking hands.",
    "The largest cup of coffee ever made held over 6,000 gallons.",
    "The tallest sandcastle ever built stood over 57 feet tall.",
    "The longest recorded time a person held their breath underwater exceeded 24 minutes.",
    "The largest hamburger ever made weighed over 2,000 pounds.",
    "The largest collection of rubber ducks by one individual numbered in the thousands.",
    "The longest fingernails ever grown on record took several decades to reach their final length.",
    "The world's tallest hotel stands over 1,600 feet high.",
    "The largest game of musical chairs involved thousands of participants at once.",
    "The fastest time to solve a Rubik's Cube by a human is under four seconds.",
    "The longest recorded marathon dance event lasted more than five days.",
    "The largest snowman ever built stood over 100 feet tall.",
    "The most consecutive hula hoop rotations recorded exceeded 100 in a single minute by top competitors.",
    "The world's largest chocolate sculpture weighed several tons.",
    "The longest fingernail growth on toes has also been separately recorded and documented.",
    "The largest group hug on record involved thousands of people simultaneously.",
    "The fastest time to type the alphabet on a keyboard is under two seconds.",
    "The longest domino chain ever toppled involved millions of individual dominoes.",
    "The tallest LEGO tower ever built stood taller than many actual buildings.",
    "The largest umbrella ever made had a diameter wider than a basketball court.",
    "The most people simultaneously blowing bubbles set a record with thousands of participants.",
    "The largest slice of cake ever cut weighed several tons.",
    "The longest fingernail beard grown as a novelty world record took years to cultivate.",
    "The largest gathering of twins in one place involved thousands of twin pairs.",
    "The fastest a person has ever run backward covered 100 meters in under 14 seconds.",
    "The largest kaleidoscope ever built stood several stories tall.",
    "The most people simultaneously jumping on pogo sticks set a record with hundreds of participants.",
    "The world's largest ball of paint has grown to weigh several tons after countless coats.",
    "The longest game of Monopoly ever played lasted over 70 days.",
    "The tallest stack of pancakes ever built stood several feet high.",
    "The largest simultaneous water balloon fight involved tens of thousands of balloons.",

    ## Miscellaneous
    "The inventor of the Pringles can is now buried in one.",
    "A group of flamingos can be seen standing on one leg partly to conserve body heat.",
    "The shortest commercial flight in the world lasts under two minutes, connecting two islands in Scotland.",
    "The color orange was named after the fruit, not the other way around.",
    "The dot on top of a lowercase 'i' or 'j' is technically called a tittle.",
    "A jiffy is an actual unit of time, referring to 1/100th of a second.",
    "The unicorn is the national animal of Scotland.",
    "It's estimated that around 10% of the world's population is left-handed.",
    "The average person spends about six months of their life waiting for red lights to turn green.",
    "The Twitter bird's official name is Larry.",
    "The longest wedding veil in the world stretched longer than 60 football fields.",
    "The inventor of the frisbee, Walter Morrison, passed away shortly after the toy's 50th anniversary.",
    "The 'save' icon on many programs is still based on the design of a floppy disk.",
    "A bolt of lightning is about five times hotter than the surface of the sun, worth repeating for how surprising it is.",
    "The world's quietest room is so silent that people can hear their own heartbeat and blood flow.",
    "The Eiffel Tower can be 15 centimeters taller during hot summer days due to metal expansion.",
    "Bubble wrap was originally invented as a textured wallpaper before being repurposed for packaging.",
    "The longest recorded game of chess between two grandmasters lasted over 20 hours.",
    "The average person will spend roughly 25 years of their life asleep.",
    "The word 'set' has the most definitions of any word in the English dictionary.",
    "The Great Wall of China is not actually visible from space with the naked eye, despite the popular myth.",
    "There's a museum entirely dedicated to the history and art of bad art, located in Massachusetts.",
    "A crowd of just 23 people has more than a 50% chance of sharing a birthday, due to probability math.",
    "The longest wedding cake ever built stretched for over half a mile.",
    "It's estimated that about 1 in 10 people have a fear of clowns.",
    "The world's smallest reptile was discovered on an island and can fit comfortably on a human fingertip.",
    "The number zero was not part of the earliest known number systems, but was developed later independently in several cultures.",
    "The world's first flushing toilet was invented in the late 1500s.",
    "A rainbow can only be seen when the sun is behind the observer and rain is in front of them.",
    "The average person forgets around 40% of new information within just 24 hours of learning it.",
    "The word 'checkmate' in chess comes from a Persian phrase meaning 'the king is helpless.'",
    "Coca-Cola was originally green before its recognizable red branding became standard.",
    "The inventor of the modern parachute successfully tested it by jumping from a bridge into the ocean.",
    "The world's largest maze made from a cornfield spans several dozen acres.",
    "There is an official 'National Talk Like a Pirate Day' celebrated every September.",
    "Bubblegum flavoring was invented before the recipe for making it less sticky was ever perfected.",
    "The number of possible unique games of chess vastly exceeds the number of atoms in the observable universe.",
    "The original name for the search engine Google was 'Backrub.'",
    "A single cloud can contain more water than the volume of an entire lake, depending on its size and density.",
    "The longest recorded yawn contagion chain involved dozens of people yawning in sequence after watching just one video.",]
