def show_help():
    print("")
    print("╔══════════════════════════════════════╗")
    print("║          🤖 My-AI Help Menu          ║")
    print("╚══════════════════════════════════════╝")

    print("")
    print("💬 CONVERSATION")
    print("-------------------------")
    print("Greet My-AI")
    print("Ask My-AI its name")
    print("Have a basic conversation")

    print("")
    print("🧠 PERSONAL MEMORY")
    print("-------------------------")
    print("Remember your name")
    print("Remember where you live")
    print("Remember things you like")
    print("Remember things you dislike")
    print("Remember your favorite foods")
    print("Remember your favorite games")
    print("Ask My-AI what it remembers")
    print("Forget something My-AI remembers")

    print("")
    print("📚 KNOWLEDGE")
    print("-------------------------")
    print("Teach My-AI new facts")
    print("Ask My-AI about learned facts")
    print("Show everything My-AI has learned")
    print("Update learned facts")
    print("Forget learned facts")

    print("")
    print("🛠️ UTILITIES")
    print("-------------------------")
    print("Tell the current time")
    print("Tell today's date")
    print("Calculate mathematical expressions")

    print("")
    print("🎮 GAMES & FUN")
    print("-------------------------")
    print("Flip a coin")
    print("Roll a dice")
    print("Play Rock, Paper, Scissors")
    print("Solve riddles")
    print("Tell jokes")
    print("Share interesting facts")
    print("Share quotes")

    print("")
    print("💡 EXAMPLES")
    print("-------------------------")
    print('Say "What is today's date?"')
    print('Say "What is my favorite game?"')
    print('Say "Teach: The capital of Australia is Canberra"')
    print('Say "I like football"')
    print('Say "I dislike spinach"')
    print('Say "What do you remember?"')

    print("")
    print("🚪 SYSTEM")
    print("-------------------------")
    print("Type 'help' to see this menu again")
    print("Type 'bye' to exit My-AI")

    print("")
    print("════════════════════════════════════════")
    print("💬 You don't need exact commands.")
    print("   Just talk naturally!")
    print("════════════════════════════════════════")
