def show_help():
    print("")
    print("📋 My-AI Commands")
    print("-------------------------")
    print("Greet you")
    print("Remember your name")
    print("Tell the time")
    print("Tell today's date")
    print("Calculate")
    print("Flip a coin")
    print("Roll a dice")
    print("Play Rock, Paper, Scissors")
    print("Ask you riddles")
    print("Tell jokes")
    print("Share facts")
    print("Share quotes")
    print("Exit (bye)")
    print("-------------------------")
    print("Just type the feature name to use it!")
