def show_help():
    print("")
    print("📋 My-AI Commands")
    print("-------------------------")
    print("hello")
    print("what is your name")
    print("date")
    print("time")
    print("calculator")
    print("coin flip")
    print("dice")
    print("rock paper scissors / rps")
    print("riddle")
    print("tell me a joke")
    print("give me a fact")
    print("give me a quote")
    print("bye")
