jokes = [ #---------- Animals ----------
  "Why don't scientists trust atoms? Because they make up everything.",
  "Why did the chicken join a band? Because it had the drumsticks.",
  "What do you call a fish with no eyes? A fsh.",
  "Why do seagulls fly over the sea? Because if they flew over the bay, they'd be bagels.",
  "What do you call a bear with no teeth? A gummy bear.",
  "Why don't oysters share their pearls? Because they're shellfish.",
  "What do you call a sleeping bull? A bulldozer.",
  "Why did the cow win an award? Because it was outstanding in its field.",
  "What do you call an alligator in a vest? An investigator.",
  "Why did the spider go to the computer? To check its website.",
  "What do you call a pig that does karate? A pork chop.",
  "How do you catch a squirrel? Climb a tree and act like a nut.",
  "What do you call a dog that can do magic? A labracadabrador.",
  "Why don't elephants use computers? They're afraid of the mouse.",
  "What do you call a fish wearing a bowtie? Sofishticated.",
  "Why did the duck get promoted? Because it was outstanding at quacking under pressure.",
  "What's a cat's favorite color? Purr-ple.",
  "Why do cows wear bells? Because their horns don't work.",
  "What do you call a snail on a ship? A snailor.",
  "Why did the horse sit down? Because it couldn't stand the neigh-sayers.",
  "What do you call a group of unorganized cats? A cat-astrophe.",
  "Why don't fish play basketball? They're afraid of the net.",
  "What did the mother buffalo say to her son as he left for school? Bison.",
  "Why did the rooster cross the road? To prove he wasn't chicken.",
  "What's a frog's favorite drink? Croak-a-cola.",
  "Why can't you give a lion a bath? Because he's the king of the shower.",
  "What do you call a bee that can't make up its mind? A maybe.",
  "Why did the owl invite his friends over? Because he didn't want to be owl by himself.",
  "What do you call a pig at a car wash? Nothing, it just squeals.",
  "Why did the crab never share? Because he's a little shellfish.",
  "What do you call a deer with no eyes? No idea.",
  "Why did the kangaroo stop drinking coffee? It made her too jumpy.",
  "What do you call a cow that plays music? A moo-sician.",
  "Why don't leopards ever escape the zoo? They're always spotted.",
  "What do you call a dinosaur that crashes his car? Tyrannosaurus wrecks.",
  "Why did the turkey cross the road twice? To prove he wasn't chicken either.",
  "What do you call a fish that needs help with music? Auto-tuna.",
  "Why did the octopus beat the shark in a fight? Because it was well armed.",
  "What do you call a bear stuck in the rain? Drizzly bear.",
  "Why did the chicken go to the seance? To talk to the other side.",
  "What do you call an owl who does magic tricks? Hoo-dini.",
  "Why did the flamingo stand on one leg? Because if it lifted both, it'd fall over.",
  "What's a shark's favorite letter? C.",
  "Why did the fish blush? Because it saw the ocean's bottom.",
  "What do you call a lazy kangaroo? Pouch potato.",
  "Why don't giraffes have many friends? They have long necks to be picky about who's close.",
  "What do you call a pony with a cough? A little hoarse.",
  "Why did the mushroom go to the party? Because he was a fungi.",
  "What do you call a cow in an earthquake? A milkshake.",
  "Why did the panda go to art school? Because it wanted to draw its own conclusions.",
  "What do you call a rabbit with fleas? Bugs Bunny.",
  "Why did the beaver cross the road? To get to the other tide.",
  "What do you call a fish without any teeth? A gummy fish.",
  "Why did the parrot wear a raincoat? In case of Polly-showers.",
  "What do you call a snake that works for the government? A civil serpent.",
  "Why did the elephant paint its toenails red? So it could hide in a strawberry patch.",
  "What do you call a very sad cup of coffee? A depresso.",
  "Why did the cat sit on the computer? To keep an eye on the mouse.",
  "What do you call a camel with no humps? Humphrey.",
  "Why did the sloth cross the road? Ask him next week.",

  #---------- Food ----------
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "What do you call cheese that isn't yours? Nacho cheese.",
  "Why did the banana go to the doctor? Because it wasn't peeling well.",
  "What do you call a fake noodle? An impasta.",
  "Why did the cookie go to the hospital? Because it felt crummy.",
  "What do you call a sad strawberry? A blueberry.",
  "Why did the grape stop in the middle of the road? Because it ran out of juice.",
  "What do you call an egg that tells jokes? A comedi-egg.",
  "Why did the coffee file a police report? It got mugged.",
  "What do you call bread that's up to no good? A rebel roll.",
  "Why did the orange lose the race? It ran out of juice.",
  "What do you call cheese made backwards? Esehc.",
  "Why did the pizza chef stop making dough? He kneaded a break.",
  "What do you call two peas that got married? Newly-weds.",
  "Why don't you ever see hamburgers in outer space? Because they can't meat the deadline.",
  "What do you call an avocado that just won the lottery? Rich, and toast is jealous.",
  "Why did the potato blush? Because it saw the salad dressing.",
  "What do you call a cheese that isn't yours? Provolone-ly.",
  "Why did the muffin go to therapy? It had too many crumbs to deal with.",
  "What's a vegetable's favorite type of music? Beet-box.",
  "Why did the lettuce win the race? It was ahead by a head.",
  "What do you call a nervous jelly? A wobbly jam.",
  "Why don't eggs tell secrets? Because they might crack.",
  "What do you call a pasta that's a spy? An impasta undercover.",
  "Why did the biscuit cry? Because its mother was a wafer so long.",
  "What do you call a snowman with a six-pack? An abdominal snowman.",
  "Why did the sausage get a promotion? It knew how to link up with people.",
  "What do you call an angry pea? A grump-kin.",
  "Why did the melon jump into the lake? It wanted to be a watermelon.",
  "What do you call a chili that plays sports? An athle-jalapeño.",
  "Why did the taco go to the gym? To get a little more filling.",
  "What do you call a sad piece of toast? A crumb-bum.",
  "Why did the carrot blush at the party? It saw the ranch dip.",
  "What do you call cheese that's always crying? Blue cheese.",
  "Why did the onion win an award? Because it made everyone cry with joy.",
  "What do you call a fish sandwich that tells jokes? Punny tuna.",
  "Why did the bagel apply for a job? It kneaded the dough.",
  "What do you call a shy pepper? A little jalapeño-shy.",
  "Why did the soup take a day off? It was feeling a little broth-en.",
  "What do you call a pie that's always in trouble? A crust-fallen dessert.",
  "Why did the doughnut go to the dentist? To get a hole filled.",
  "What do you call a cow that eats your grass? A lawn moo-er.",
  "Why did the sandwich stop telling jokes? The bread kept going stale.",
  "What do you call fruit that's always angry? A grumpy grape.",
  "Why did the pancake go to school? To get a little flatter education.",
  "What do you call cheese made of milk from a nervous cow? Nervous-cheese.",
  "Why did the cupcake go to school? To get a little icing on its education.",
  "What do you call a potato that plays basketball? A hash-slam dunk.",
  "Why did the corn keep to itself? It was a little husky.",
  "What do you call a nut that laughs a lot? A cashew-ally funny nut.",
  "Why did the celery break up with the carrot? It felt taken for granite.",
  "What do you call a fruit that's always cold? A frosty berry.",
  "Why did the sushi roll blush? Because it saw the wasabi.",
  "What do you call an apple that plays trumpet? A tooty-fruity.",
  "Why did the waffle apply for a job? To get a little more batter pay.",
  "What do you call a soup that tells the truth? Honest broth.",
  "Why did the peanut go to school? To get a little more shell-education.",
  "What do you call a pretzel that's a detective? A twisty sleuth.",
  "Why did the milk go to school? Because it wanted to be pasteurized.",

  #---------- Science and Math ----------
  "Why can't you trust an atom? Because they make up everything.",
  "Why did the physicist break up with the biologist? There was no chemistry.",
  "Why are chemists great for solving problems? They have all the solutions.",
  "Why did the math book look sad? Because it had too many problems.",
  "What did zero say to eight? Nice belt.",
  "Why was the equal sign so humble? Because it knew it wasn't less than or greater than anyone.",
  "Why couldn't the angle get a loan? Its parents wouldn't cosine.",
  "What do you call a number that can't sit still? A roamin' numeral.",
  "Why did the student wear glasses in math class? To improve di-vision.",
  "What do you call an acid with an attitude? A-mean-o acid.",
  "Why did the scarecrow win a Nobel Prize? He was outstanding in his field.",
  "Why do programmers prefer dark mode? Because light attracts bugs.",
  "Why did the biologist go to the beach? To study the current-cy.",
  "What's a physicist's favorite food? Fission chips.",
  "Why did the electron break up with the proton? It found someone more positive.",
  "What do you call a fish made of two sodium atoms? NaFish.",
  "Why did Newton avoid social gatherings? He didn't like the reaction.",
  "How does the moon cut its hair? Eclipse it.",
  "Why did the geologist break up with his girlfriend? She took him for granite.",
  "What do you call a boomerang that doesn't come back? A stick.",
  "Why don't scientists trust stairs? Because they're always up to something.",
  "What's the difference between a chemist and a magician? One makes solutions, the other makes people disappear.",
  "Why did the calculator apologize? It felt like it made a miscalculation.",
  "What do you call an educated tube? A graduated cylinder.",
  "Why was the mushroom always invited to parties? He was a fungi to be with.",
  "Why did the astronaut break up with his girlfriend? He needed space.",
  "What do you call a group of astronomers who moved to a new galaxy? Astro-nomads.",
  "Why did the star go to school? To get brighter.",
  "What's a math teacher's favorite dessert? Pi.",
  "Why did the triangle refuse to fight the circle? It didn't have a point.",
  "What did one wall say to the other wall? I'll meet you at the corner.",
  "Why was the equation feeling great? It found balance.",
  "What do you call an alligator working for the FBI? An investi-gator.",
  "Why don't skeletons fight each other? They don't have the guts.",
  "What did the janitor say when he jumped out of the closet? Supplies!",
  "Why did the germ cross the microscope? To get to the other slide.",
  "What do you call a computer that sings? A Dell.",
  "Why couldn't the leopard hide? He was always spotted.",
  "Why did the physics teacher break up with the chemistry teacher? No chemistry, only friction.",
  "What do you call two atoms that always hang out? Best-friends bonded together.",
  "Why did the volcano stop erupting? It was all out of magma-tion.",
  "Why did the graph paper feel important? It always had a point to make.",
  "What's a nuclear scientist's favorite snack? Fission chips too.",
  "Why did the computer keep sneezing? It had a virus.",
  "What do you call an origami astronaut? A folded space case.",
  "Why did the light bulb fail math class? It wasn't very bright at multiplying.",
  "What's a snake's favorite subject? Hiss-tory.",
  "Why did the biology teacher's class smell funny? They were studying odor-ganisms.",
  "What do you call a really tall mathematician? A high-figure.",
  "Why did the robot go on a diet? Too many bytes.",
  "What did the scientist say when he found two isotopes of helium? He he.",
  "Why do statisticians make great fishermen? They know the median.",
  "What do you call a dinosaur with a great vocabulary? A thesaurus.",
  "Why did the string not want to play with the other strings? He was a frayed knot.",
  "What did one DNA strand say to the other? Do these genes make me look fat?",
  "Why couldn't the astronomer sleep? He was thinking too much about the space between stars.",
  "What do you call a scientist who studies bad smells? An odor-nithologist.",
  "Why did the mathematician spill all his food in the pan? He was told to always use a level.",
  "What do you call a computer that plays music? A Dell speaker.",
  "Why did the calculator feel lonely? It had no one to count on.",

  #---------- Computers and Tech ----------
  "Why do programmers prefer dark mode? Because light attracts bugs.",
  "Why did the developer go broke? Because he used up all his cache.",
  "How many programmers does it take to change a light bulb? None, that's a hardware problem.",
  "Why do Java developers wear glasses? Because they don't C#.",
  "What's a computer's favorite snack? Microchips.",
  "Why was the JavaScript developer sad? Because he didn't know how to null his feelings.",
  "Why did the computer go to therapy? It had too many unresolved issues.",
  "What do you call a computer that tells jokes? A stand-up server.",
  "Why did the programmer quit his job? He didn't get arrays.",
  "What's the object-oriented way to become wealthy? Inheritance.",
  "Why do programmers hate nature? It has too many bugs.",
  "Why did the computer keep freezing? It left its Windows open.",
  "What do you call a group of eight hobbits? A hobbyte.",
  "Why don't robots panic? They have nerves of steel, literally.",
  "Why did the software engineer bring a ladder to work? To reach the high-level code.",
  "What's a robot's favorite type of music? Heavy metal.",
  "Why was the smartphone always tired? Too many apps running.",
  "What do you call a printer that sings? A jam session.",
  "Why did the AI go to school? To improve its neural net-working.",
  "What's a computer virus's favorite genre? Malware-ck (dark comedy).",
  "Why did the wifi break up with the router? It felt disconnected.",
  "What do you call a spider that hacks computers? A web developer.",
  "Why did the keyboard break up with the mouse? It needed some space.",
  "What do you call a robot who always takes the long way? R2-detour.",
  "Why did the code go to the doctor? It had a bad case of syntax error.",
  "What's a hacker's favorite season? Phishing season.",
  "Why did the laptop go to the beach? To get a byte of sun.",
  "What do you call a computer that sings opera? A high-decibel-drive.",
  "Why did the software update take so long? It had a lot of baggage.",
  "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
  "Why did the programmer stay in bed? He was running in his sleep mode.",
  "What do you call an app that helps you nap? A snoozeSDK.",
  "Why did the drone break up with the remote? It needed its own space.",
  "What's a computer's favorite dance? The algo-rhythm.",
  "Why did the phone go to therapy? It had too many missed connections.",
  "What do you call a robot that takes the scenic route? A round-about-bot.",
  "Why did the email get rejected? It had too much attachment issues.",
  "What's a database's favorite type of music? SQL and roll.",
  "Why don't programmers like the outdoors? There's a bug there they can't just Ctrl+Z.",
  "What do you call a computer floating in the ocean? A screensaver.",
  "Why did the app break up with its user? It needed some updates.",
  "What's a cloud's favorite kind of storage? Self storage.",
  "Why did the network go silent? It lost its connection.",
  "What do you call a byte that tells jokes? A bit funny.",
  "Why did the firewall get promoted? It really knew how to block out distractions.",
  "What do you call an old computer? A pentium-sioner.",
  "Why did the robot get in trouble at school? For cutting classes to recharge.",
  "What's a router's favorite genre of movie? Wireless action films.",
  "Why did the programmer's parrot learn to code? To pick up bad habits, obviously.",
  "What do you call an AI that tells great one-liners? A punline generator.",
  "Why did the modem apply for a loan? It needed to upgrade its connections.",
  "What's a keyboard's favorite exercise? Shift work.",
  "Why did the algorithm break up with the dataset? It found someone with better patterns.",
  "What do you call two robots dating? Byte-mates.",
  "Why did the computer sneeze? It caught a bug from the internet.",
  "What's a hard drive's favorite hobby? Spinning tales.",
  "Why did the programmer bring string to the interview? For all the loose ends.",
  "What do you call a slow computer that tells jokes? A lag-comedian.",
  "Why did the software crash at the party? It couldn't handle the load.",
  "What's an app's favorite excuse? It needs to update first.",

  #---------- Dad jokes ----------
  "I used to be a banker, but I lost interest.",
  "I only know 25 letters of the alphabet. I don't know y.",
  "What do you call a factory that makes okay products? A satisfactory.",
  "I told my wife she should embrace her mistakes. She gave me a hug.",
  "I'm reading a book about anti-gravity. It's impossible to put down.",
  "I used to hate facial hair, but then it grew on me.",
  "Did you hear about the guy who invented Lifesavers? He made a mint.",
  "I would tell you a chemistry joke, but I know I wouldn't get a reaction.",
  "I stayed up all night wondering where the sun went, then it dawned on me.",
  "The rotation of Earth really makes my day.",
  "I don't trust stairs. They're always up to something.",
  "I used to be indecisive. Now I'm not so sure.",
  "I'm on a seafood diet. I see food and I eat it.",
  "What do you call a fish with no eyes? A fsh, still funny the second time.",
  "I wondered why the ball kept getting bigger. Then it hit me.",
  "Why do bicycles fall over? Because they're two-tired.",
  "I once got a job at a bakery because I kneaded dough.",
  "What's the best time to go to the dentist? Tooth-hurty.",
  "I'm friends with 25 letters of the alphabet. I don't know y.",
  "Time flies like an arrow. Fruit flies like a banana.",
  "I told a chemistry teacher joke, there was no reaction.",
  "I bought shoes from a drug dealer. I don't know what he laced them with, but I've been tripping all day.",
  "What do you call a can opener that doesn't work? A can't opener.",
  "I got a job at a calendar factory, but I got fired for taking a day off.",
  "The shovel was a groundbreaking invention.",
  "Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.",
  "I used to play piano by ear, now I use my hands.",
  "I had a dream I was a muffler last night. I woke up exhausted.",
  "What do you call a factory worker who makes puns? A pun-cher.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "I told my doctor I broke my arm in two places. He told me to stop going to those places.",
  "How do you organize a space party? You planet.",
  "I got fired from the bank today. An old lady asked me to check her balance, so I pushed her over.",
  "I invented a new word: Plagiarism.",
  "I couldn't figure out why the baseball kept getting closer, then it hit me.",
  "The past, present, and future walked into a bar. It was tense.",
  "I'm terrified of elevators, so I'm going to start taking steps to avoid them.",
  "Why don't scientists trust atoms anymore? They make up everything, and I mean everything.",
  "I told my wife I was going to fix the car with duct tape. She said don't be ridiculous, but it worked out.",
  "I was going to look for my missing watch, but I could never find the time.",
  "What do you call a boomerang that won't come back? A stick, and a sad one at that.",
  "Have you heard about the corduroy pillow? It's making headlines.",
  "I recently decided to sell my vacuum cleaner. It was just gathering dust.",
  "What do you call cheese that's not yours? Nacho cheese, again, still funny.",
  "I'm reading a book on the history of glue. I can't put it down.",
  "I used to be a personal trainer, but I lost my drive.",
  "I got a great deal on a used elevator. It has its ups and downs.",
  "What did the ocean say to the shore? Nothing, it just waved.",
  "I asked the librarian if the library had books on paranoia. She whispered, they're right behind you.",
  "How does a penguin build its house? Igloos it together.",
  "I was addicted to the hokey pokey, but I turned myself around.",
  "What do you call a very small valentine? A valen-tiny.",
  "I have a joke about construction, but I'm still working on it.",
  "I've started telling everyone about the benefits of eating dried grapes. It's all about raisin awareness.",
  "The man who invented knock-knock jokes should get a no-bell prize.",
  "I asked my dog what's two minus two, he said nothing.",
  "I used to have a fear of hurdles, but I got over it.",
  "The math teacher called in sick with algebra. They think he has a problem with a variable.",
  "My boss told me to have a good day, so I went home.",
  "I decided to sell my Hoover, well it was just collecting dust.",

  #---------- Work and Office ----------
  "Why did the employee bring a ladder to work? To reach the next level.",
  "Why don't office workers ever get cold? They stay close to the space heater of deadlines.",
  "What's the difference between a job interview and a first date? Not much, both need good answers.",
  "Why did the manager bring a mirror to the meeting? To see reflections on the quarter.",
  "Why don't accountants ever get lost? They always know how to count on themselves.",
  "What do you call a boss that never stops talking? A never-ending meeting.",
  "Why did the resume go to therapy? It had too many gaps to deal with.",
  "What do you call a coworker who's always calm? A stress-free zone.",
  "Why did the intern bring a map to work? To find the career path.",
  "What's an office's favorite type of exercise? Jumping to conclusions.",
  "Why did the printer get promoted? For consistently delivering output.",
  "What do you call a meeting that never ends? A loop-hole.",
  "Why did the employee take a photo of the ceiling? For the perfect roof-top view meeting.",
  "What do you call a productive Monday? A rare unicorn sighting.",
  "Why did the stapler get a promotion? Because it always held things together.",
  "What's the office's favorite type of coffee? De-caf-feinated deadlines.",
  "Why did the spreadsheet break up with the calculator? It needed space to grow.",
  "What do you call a boss who never listens? Deaf-adline maker.",
  "Why did the employee bring string to work? To tie up loose ends.",
  "What's the difference between a meeting and a hostage situation? In a hostage situation, there's a chance of ransom.",
  "Why did the office chair go to therapy? It had too much pressure sitting on it.",
  "What do you call a coworker who never says no? A yes-man in disguise.",
  "Why did the paperclip go missing? It got attached to someone else.",
  "What's an office party's favorite drink? Spreadsheet punch.",
  "Why did the employee bring an umbrella to the meeting? In case of a brainstorm.",
  "What do you call a workplace with no deadlines? A fantasy.",
  "Why did the calendar go to therapy? Too many dates fell through.",
  "What's the best way to start a Monday morning meeting? With coffee and low expectations.",
  "Why did the desk get promoted? It always supported everyone above it.",
  "What do you call an overly cautious employee? A safety-net worker.",
  "Why did the whiteboard feel appreciated? Everyone kept writing about it.",
  "What's an office's least favorite season? Performance review season.",
  "Why did the coworker bring a compass to the meeting? To find direction in the discussion.",
  "What do you call two colleagues who never agree? A perpetual debate club.",
  "Why did the intern get lost in the office? No one gave clear directions.",
  "What's the office's favorite game? Pass the blame.",
  "Why did the manager bring a whistle to the meeting? To call time-outs on bad ideas.",
  "What do you call a well-organized inbox? A myth.",
  "Why did the employee bring a flashlight to work? To find the light at the end of the deadline.",
  "What's an office chair's favorite hobby? Spinning tales.",
  "Why did the coworker bring headphones to the meeting? To tune out unnecessary noise.",
  "What do you call a boss who takes credit for everything? A spotlight hog.",
  "Why did the employee bring a fan to work? To cool down heated discussions.",
  "What's the difference between a good and bad meeting? About an hour.",
  "Why did the office plant get promoted? It always grew with the company.",
  "What do you call a team that never communicates? A silent movie.",
  "Why did the employee bring a raincoat to the meeting? In case it rained criticism.",
  "What's an office's favorite bird? The early riser.",
  "Why did the coworker bring a puzzle to work? To piece together the project.",
  "What do you call an employee who's always on time? A rare species.",
  "Why did the boss bring a magnifying glass to the review? To look closer at the details.",
  "What's the office's favorite exercise machine? The treadmill of endless tasks.",
  "Why did the employee bring an alarm clock to the meeting? To wake up the discussion.",
  "What do you call a team that finishes early? A miracle.",
  "Why did the coworker bring a shovel to work? To dig deeper into the report.",
  "What's an office's favorite dessert? Deadline pie, served cold.",
  "Why did the manager bring binoculars to the office? To see the big picture.",
  "What do you call an inbox with zero unread emails? A fairy tale.",
  "Why did the coworker bring a kite to the meeting? To keep ideas flying high.",
  "What's the best way to survive a long meeting? Bring snacks and low expectations.",

  #---------- School ----------
  "Why did the student eat his homework? Because the teacher said it was a piece of cake.",
  "Why did the pencil go to school? To get a little sharper.",
  "What's a teacher's favorite snack? Smarties.",
  "Why did the boy bring a ladder to school? He wanted to go to high school.",
  "What do you call a teacher who never smiles? A grade-A grump.",
  "Why did the calculator go to the principal's office? For being too calculating.",
  "What's a school's favorite type of music? Class-ical.",
  "Why did the student bring a map to class? To find his way through the syllabus.",
  "What do you call a student who's always late? A tardy artist.",
  "Why did the notebook get in trouble? It had too many unfinished pages.",
  "What's a library's favorite genre? Fiction, because it always checks out.",
  "Why did the eraser feel useless? It kept getting rubbed the wrong way.",
  "What do you call a school that floats? Elementary, my dear.",
  "Why did the ruler get a promotion? It always measured up.",
  "What's a student's favorite subject in winter? Snow-cial studies.",
  "Why did the backpack go on a diet? Too many heavy textbooks.",
  "What do you call a teacher's favorite country? Germany, because it's full of dis-ciples.",
  "Why did the student bring a ladder to the exam? To reach a higher grade.",
  "What's a math class's favorite dessert? Pi, always.",
  "Why did the chalk feel nervous? It didn't want to be taken for granted.",
  "What do you call a nervous test taker? A cram-champion.",
  "Why did the crayon go to school? To draw its own conclusions.",
  "What's the noisiest classroom subject? Band practice.",
  "Why did the locker feel lonely? Everyone kept passing by without stopping.",
  "What do you call a student who's always studying? A book-worm-in-training.",
  "Why did the school bus break down? It ran out of school spirit.",
  "What's a history teacher's favorite drink? Old-fashioned tea.",
  "Why did the student bring a flashlight to class? To lighten up the lecture.",
  "What do you call a class that never stops talking? Recess, basically.",
  "Why did the pencil case feel proud? It held everything together.",
  "What's a science class's favorite game? Hide and go seek the beaker.",
  "Why did the student fail the ocean exam? Because it was way too deep for him.",
  "What do you call a classroom full of clocks? A ticking time-table.",
  "Why did the desk feel overworked? Too many assignments piling up.",
  "What's a teacher's favorite exercise? Extra-curricular jumping to conclusions.",
  "Why did the report card feel nervous? Too many grades on the line.",
  "What do you call a school with no rules? A dream, briefly.",
  "Why did the student bring string to the geometry class? To measure up perfectly.",
  "What's an art class's favorite phrase? Draw your own conclusions.",
  "Why did the whiteboard marker feel confident? It always left a mark.",
  "What do you call a class trip that never happens? A permission slip nightmare.",

  #---------- Sports ----------
  "Why did the golfer bring two shirts? In case he got a hole in one.",
  "Why don't basketball players like vacations? They're afraid of travelling.",
  "What do you call a boxer who tells jokes? A comedi-hitter.",
  "Why did the soccer player bring string to the game? To tie the score.",
  "What's a runner's favorite subject? Fast-tory.",
  "Why did the football coach go to the bank? To get his quarterback.",
  "What do you call a fish that plays baseball? A pitcher.",
  "Why did the tennis player bring a ladder? To reach a higher serve.",
  "What's a swimmer's favorite type of music? Pool-side beats.",
  "Why did the baseball player bring a suitcase? For a long stay at first base.",
  "What do you call a cyclist who never stops? A wheel deal.",
  "Why did the boxer break up with his girlfriend? He wanted to punch above his weight elsewhere.",
  "What's a wrestler's favorite drink? Ice tea, no throws.",
  "Why did the referee bring a whistle to dinner? Out of habit.",
  "What do you call a horse that plays soccer? A stable striker.",
  "Why did the runner never win? He kept losing his train of thought.",
  "What's a hockey player's favorite snack? Ice chips.",
  "Why did the basketball player bring an umbrella? In case of a rain-check.",
  "What do you call a skier who tells great jokes? A slope-comedian.",
  "Why did the cricket player bring a diary? To keep track of his innings.",
  "What's a gymnast's favorite dessert? Flip-cakes.",
  "Why did the archer bring a map? To find his target audience.",
  "What do you call a marathon runner who never finishes? A perpetual work in progress.",
  "Why did the goalkeeper bring a net to dinner? Old habits.",
  "What's a rugby player's favorite drink? A scrum-cha tea.",
  "Why did the surfer bring a book? To catch up on some waves of knowledge.",
  "What do you call a fisherman who plays chess? A reel strategist.",
  "Why did the volleyball team win the championship? They knew how to set each other up.",
  "What's a bowler's favorite type of humor? Strike-comedy.",
  "Why did the athlete bring a calendar to practice? To mark his personal records.",

  #---------- Weather and Nature ----------
  "Why did the cloud break up with the sky? It needed some space to rain elsewhere.",
  "What do you call a snowman in July? A puddle.",
  "Why did the sun go to school? To get brighter every day.",
  "What's a tornado's favorite dance? The twist.",
  "Why did the tree go to the dentist? It needed a root canal.",
  "What do you call a rock that never works? A little boulder than the rest, lazy.",
  "Why did the leaf go to the doctor? It was feeling green.",
  "What's a river's favorite subject? Current events.",
  "Why did the mountain go to therapy? It had too many peaks and valleys.",
  "What do you call fog that tells jokes? A mist-erious comedian.",
  "Why did the flower blush? Because the bee said sweet things.",
  "What's a volcano's favorite exercise? Lava-lifting.",
  "Why did the wind break up with the storm? It needed some calm.",
  "What do you call a raindrop having a bad day? Under the weather, literally.",
  "Why did the desert never get thirsty? It always had sandwiches.",
  "What's a lake's favorite type of story? A deep one.",
  "Why did the star refuse to fight? It didn't want to cause a supernova of drama.",
  "What do you call a cloud with muscles? A thunder-bolt of strength.",
  "Why did the moon skip dinner? It was already full.",
  "What's an iceberg's favorite type of humor? Cool and dry.",
  "Why did the rainbow feel appreciated? Everyone always pointed it out.",
  "What do you call a forest that tells jokes? A trees-tand-up comedian.",
  "Why did the beach never get bored? It always had waves of activity.",
  "What's a hurricane's favorite game? Twister.",
  "Why did the snowflake feel special? Because no two are ever alike.",
  "What do you call a plant that's a detective? A sherlock of the soil.",
  "Why did the field feel proud? It was always outstanding.",
  "What's a canyon's favorite music genre? Echo-chamber pop.",
  "Why did the star go to school? To improve its shine-tellectual growth.",
  "What do you call the ocean at night? A little shore of darkness, calm.",

  #---------- Music ----------
  "Why did the musician bring a ladder to the gig? To hit the high notes.",
  "What do you call a musical cow? A moo-sician, once more with feeling.",
  "Why did the guitar go to therapy? It had too many strings attached.",
  "What's a drummer's favorite vegetable? Beets.",
  "Why did the piano get locked out? It couldn't find the right key.",
  "What do you call an opera singer who tells jokes? A high-note comedian.",
  "Why did the violin break up with the cello? It felt like there was too much tension.",
  "What's a trumpet's favorite exercise? Blowing off steam.",
  "Why did the singer bring a map on tour? To find her voice.",
  "What do you call a band that plays only for pets? A purr-cussion section.",
  "Why did the DJ get kicked out of the library? He kept dropping the bass.",
  "What's a saxophone's favorite drink? Jazz-berry tea.",
  "Why did the choir member bring an umbrella? In case of a sharp shower of notes.",
  "What do you call a song about tortillas? A wrap.",
  "Why did the harp feel calm? It always stayed in tune with itself.",
  "What's a banjo's favorite hobby? Pickin' up new skills.",
  "Why did the composer feel accomplished? He finally noted his progress.",
  "What do you call a musical potato? A chip off the old rock.",
  "Why did the flute get promoted? It always hit the right notes.",
  "What's an orchestra's favorite drink? Symphony smoothies.",
  "Why did the accordion never win an argument? It kept getting stretched thin.",
  "What do you call a rockstar vegetable? A jam-packed carrot.",
  "Why did the singer bring string to the concert? To keep the show tied together.",
  "What's a xylophone's favorite game? Note-and-seek.",
  "Why did the microphone feel important? Everyone always listened to it.",
  "What do you call a musical ghost? A boo-gie woogie master.",
  "Why did the tuba feel embarrassed? It made a big noise at the wrong time.",
  "What's a cellist's favorite fruit? A string-berry.",
  "Why did the karaoke machine break down? Too many bad notes to handle.",
  "What do you call a musical snake? A hiss-terical performer.",

  #---------- Miscellaneous puns ----------
  "Why did the scarecrow win an award? Because he was outstanding in his field, again.",
  "What do you call a fish wearing a crown? King Neptune's nephew.",
  "Why did the belt get arrested? For holding up a pair of pants.",
  "What do you call a can of soup that doesn't work? A can't of soup.",
  "Why did the clock go back to school? To learn how to tell better time.",
  "What do you call a nervous jelly bean? A jitter-bean.",
  "Why did the shoe stay home? It had a hole in its sole.",
  "What do you call an alligator detective? An investi-gator, revisited.",
  "Why did the broom get promoted? It always swept up the competition.",
  "What do you call a pile of kittens? A meowntain.",
  "Why did the candle get invited to every party? It really knew how to light up a room.",
  "What do you call a boomerang that always comes back with jokes? A pun-erang.",
  "Why did the sock go to therapy? It felt like it had a hole in its identity.",
  "What do you call a nervous ghost? A scaredy-boo.",
  "Why did the umbrella get promoted? It really knew how to handle pressure.",
  "What do you call a book about earthquakes? A page turner, quite literally.",
  "Why did the mirror feel confident? It always reflected on things clearly.",
  "What do you call a dinosaur that loves to sleep? A dino-snore.",
  "Why did the balloon get so popular? It really knew how to fill a room.",
  "What do you call a story about a broken pencil? Pointless.",
  "Why did the shoe feel important? It always tied things together.",
  "What do you call a fish that's good at negotiating? A haggle-fish.",
  "Why did the map feel confident? It always knew where it stood.",
  "What do you call a spider that's a good dancer? A web-tastic mover.",
  "Why did the candle break up with the match? It felt like it was being used.",
  "What do you call a story that never ends? A tale without a tail.",
  "Why did the pillow feel appreciated? Everyone always leaned on it.",
  "What do you call a snail that's a superhero? Shell-vester Stallone.",
  "Why did the button feel proud? It always held things together.",
  "What do you call a nervous lightbulb? A little dim, but trying.",
  "Why did the chair go to therapy? It had too much support to give.",
  "What do you call a story about socks? A footnote.",
  "Why did the calendar feel stressed? Its days were numbered.",
  "What do you call a duck that's a magician? A quack-a-doodle wizard.",
  "Why did the paintbrush feel proud? It always colored outside the lines confidently.",
  "What do you call a nervous door? A little jittery on its hinges.",
  "Why did the towel feel absorbed in its work? It always soaked things up.",
  "What do you call a spoon that tells jokes? A stirring comedian.",
  "Why did the fork feel left out? It never got to the point of the conversation.",
  "What do you call a plate that's a good listener? A dish that always takes it all in.",
  "Why did the napkin feel useful? It always wiped away the mess.",
  "What do you call a story about a broken chair? A little unbalanced.",
  "Why did the lamp feel bright? It always lit up a room.",
  "What do you call a curtain that tells jokes? A drape-comedian.",
  "Why did the rug feel walked over? Because everyone kept stepping on its punchlines.",
  "What do you call a broom that sings? A sweep-tacular performer.",
  "Why did the mop feel exhausted? It always cleaned up everyone's messes.",
  "What do you call a vacuum that tells stories? A suck-cessful narrator.",
  "Why did the window feel clear about its purpose? It always saw things from both sides.",
  "What do you call a door that tells the truth? Always open about it.",
  "Why did the key feel important? It always unlocked the best jokes.",
  "What do you call a nervous doorknob? A little turned around.",
  "Why did the ladder feel accomplished? It always reached new heights.",
  "What do you call a bucket that tells jokes? A pail comedian.",
  "Why did the hose feel refreshed? It always sprayed positivity around.",
  "What do you call a nervous garden gnome? A little rock-y on the outside.",
  "Why did the fence feel like a good listener? It always kept things in.",
  "What do you call a gate that tells stories? A swing-ing narrator.",
  "Why did the shovel feel accomplished? It always dug up the best material.",
  "What do you call a rake that's funny? A leaf-comedian.",]
